### ISSUE TITLE
Status Ailment Tracking

### ISSUE THREAD

**Issue by sesopenko** [sesopenko/dndnext-sheet#4]
_As a DM I would like to track conditions of combat participants_

Acceptance Criteria:
- [ ] Add new status ailment tracker after HP tracker
- [ ] Status ailment tracker has + button that opens text box for DM to enter condition and number of rounds into
- [ ] Current conditions are displayed with rounds remaining.
- [ ] Alt text of conditions (hover) shows number of minutes & seconds remaining in the format of X:XX
- [ ] Conditions can be removed with click of button
